/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AndroidRouteImport } from './routes/android'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as FollowersRouteImport } from './routes/followers'
import { Route as ForensicsRouteImport } from './routes/forensics'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoungeRouteImport } from './routes/lounge'
import { Route as NewFeedRouteImport } from './routes/new-feed'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StalkerRouteImport } from './routes/stalker'
import { Route as TimingRouteImport } from './routes/timing'
import { Route as ApiDownloadApkRouteImport } from './routes/api/download-apk'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronPublishRouteImport } from './routes/api/cron/publish'
import { Route as ApiCronPullRouteImport } from './routes/api/cron/pull'
import { Route as ApiLoungeDashboardRouteImport } from './routes/api/lounge/dashboard'
import { Route as ApiLoungeHookRouteImport } from './routes/api/lounge/hook'
import { Route as ApiLoungeLinkRouteImport } from './routes/api/lounge/link'
import { Route as ApiLoungePairRouteImport } from './routes/api/lounge/pair'
import { Route as ApiLoungePublishRouteImport } from './routes/api/lounge/publish'
import { Route as ApiLoungeRefreshRouteImport } from './routes/api/lounge/refresh'
import { Route as ApiLoungeReportRouteImport } from './routes/api/lounge/report'
import { Route as ApiLoungeRestoreRouteImport } from './routes/api/lounge/restore'
import { Route as ApiLoungeScheduleRouteImport } from './routes/api/lounge/schedule'
import { Route as ApiLoungeSessionRouteImport } from './routes/api/lounge/session'
import { Route as ApiLoungeStatusRouteImport } from './routes/api/lounge/status'
import { Route as ApiPhonePublishRouteImport } from './routes/api/phone/publish'
import { Route as ApiPhoneQueueRouteImport } from './routes/api/phone/queue'
import { Route as ApiPhoneSessionRouteImport } from './routes/api/phone/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AndroidRoute = AndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowersRoute = FollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForensicsRoute = ForensicsRouteImport.update({
  id: '/forensics',
  path: '/forensics',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoungeRoute = LoungeRouteImport.update({
  id: '/lounge',
  path: '/lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const NewFeedRoute = NewFeedRouteImport.update({
  id: '/new-feed',
  path: '/new-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StalkerRoute = StalkerRouteImport.update({
  id: '/stalker',
  path: '/stalker',
  getParentRoute: () => rootRouteImport,
} as any)
const TimingRoute = TimingRouteImport.update({
  id: '/timing',
  path: '/timing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadApkRoute = ApiDownloadApkRouteImport.update({
  id: '/api/download-apk',
  path: '/api/download-apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPublishRoute = ApiCronPublishRouteImport.update({
  id: '/api/cron/publish',
  path: '/api/cron/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPullRoute = ApiCronPullRouteImport.update({
  id: '/api/cron/pull',
  path: '/api/cron/pull',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungeDashboardRoute = ApiLoungeDashboardRouteImport.update({
  id: '/api/lounge/dashboard',
  path: '/api/lounge/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungeHookRoute = ApiLoungeHookRouteImport.update({
  id: '/api/lounge/hook',
  path: '/api/lounge/hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungeLinkRoute = ApiLoungeLinkRouteImport.update({
  id: '/api/lounge/link',
  path: '/api/lounge/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungePairRoute = ApiLoungePairRouteImport.update({
  id: '/api/lounge/pair',
  path: '/api/lounge/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungePublishRoute = ApiLoungePublishRouteImport.update({
  id: '/api/lounge/publish',
  path: '/api/lounge/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungeRefreshRoute = ApiLoungeRefreshRouteImport.update({
  id: '/api/lounge/refresh',
  path: '/api/lounge/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungeReportRoute = ApiLoungeReportRouteImport.update({
  id: '/api/lounge/report',
  path: '/api/lounge/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungeRestoreRoute = ApiLoungeRestoreRouteImport.update({
  id: '/api/lounge/restore',
  path: '/api/lounge/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungeScheduleRoute = ApiLoungeScheduleRouteImport.update({
  id: '/api/lounge/schedule',
  path: '/api/lounge/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungeSessionRoute = ApiLoungeSessionRouteImport.update({
  id: '/api/lounge/session',
  path: '/api/lounge/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoungeStatusRoute = ApiLoungeStatusRouteImport.update({
  id: '/api/lounge/status',
  path: '/api/lounge/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhonePublishRoute = ApiPhonePublishRouteImport.update({
  id: '/api/phone/publish',
  path: '/api/phone/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneQueueRoute = ApiPhoneQueueRouteImport.update({
  id: '/api/phone/queue',
  path: '/api/phone/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneSessionRoute = ApiPhoneSessionRouteImport.update({
  id: '/api/phone/session',
  path: '/api/phone/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/android': typeof AndroidRoute
  '/config': typeof ConfigRoute
  '/followers': typeof FollowersRoute
  '/forensics': typeof ForensicsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/lounge': typeof LoungeRoute
  '/new-feed': typeof NewFeedRoute
  '/phone': typeof PhoneRoute
  '/publish': typeof PublishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stalker': typeof StalkerRoute
  '/timing': typeof TimingRoute
  '/api/download-apk': typeof ApiDownloadApkRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/cron/pull': typeof ApiCronPullRoute
  '/api/lounge/dashboard': typeof ApiLoungeDashboardRoute
  '/api/lounge/hook': typeof ApiLoungeHookRoute
  '/api/lounge/link': typeof ApiLoungeLinkRoute
  '/api/lounge/pair': typeof ApiLoungePairRoute
  '/api/lounge/publish': typeof ApiLoungePublishRoute
  '/api/lounge/refresh': typeof ApiLoungeRefreshRoute
  '/api/lounge/report': typeof ApiLoungeReportRoute
  '/api/lounge/restore': typeof ApiLoungeRestoreRoute
  '/api/lounge/schedule': typeof ApiLoungeScheduleRoute
  '/api/lounge/session': typeof ApiLoungeSessionRoute
  '/api/lounge/status': typeof ApiLoungeStatusRoute
  '/api/phone/publish': typeof ApiPhonePublishRoute
  '/api/phone/queue': typeof ApiPhoneQueueRoute
  '/api/phone/session': typeof ApiPhoneSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/android': typeof AndroidRoute
  '/config': typeof ConfigRoute
  '/followers': typeof FollowersRoute
  '/forensics': typeof ForensicsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/lounge': typeof LoungeRoute
  '/new-feed': typeof NewFeedRoute
  '/phone': typeof PhoneRoute
  '/publish': typeof PublishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stalker': typeof StalkerRoute
  '/timing': typeof TimingRoute
  '/api/download-apk': typeof ApiDownloadApkRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/cron/pull': typeof ApiCronPullRoute
  '/api/lounge/dashboard': typeof ApiLoungeDashboardRoute
  '/api/lounge/hook': typeof ApiLoungeHookRoute
  '/api/lounge/link': typeof ApiLoungeLinkRoute
  '/api/lounge/pair': typeof ApiLoungePairRoute
  '/api/lounge/publish': typeof ApiLoungePublishRoute
  '/api/lounge/refresh': typeof ApiLoungeRefreshRoute
  '/api/lounge/report': typeof ApiLoungeReportRoute
  '/api/lounge/restore': typeof ApiLoungeRestoreRoute
  '/api/lounge/schedule': typeof ApiLoungeScheduleRoute
  '/api/lounge/session': typeof ApiLoungeSessionRoute
  '/api/lounge/status': typeof ApiLoungeStatusRoute
  '/api/phone/publish': typeof ApiPhonePublishRoute
  '/api/phone/queue': typeof ApiPhoneQueueRoute
  '/api/phone/session': typeof ApiPhoneSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/android': typeof AndroidRoute
  '/config': typeof ConfigRoute
  '/followers': typeof FollowersRoute
  '/forensics': typeof ForensicsRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/lounge': typeof LoungeRoute
  '/new-feed': typeof NewFeedRoute
  '/phone': typeof PhoneRoute
  '/publish': typeof PublishRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stalker': typeof StalkerRoute
  '/timing': typeof TimingRoute
  '/api/download-apk': typeof ApiDownloadApkRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/publish': typeof ApiCronPublishRoute
  '/api/cron/pull': typeof ApiCronPullRoute
  '/api/lounge/dashboard': typeof ApiLoungeDashboardRoute
  '/api/lounge/hook': typeof ApiLoungeHookRoute
  '/api/lounge/link': typeof ApiLoungeLinkRoute
  '/api/lounge/pair': typeof ApiLoungePairRoute
  '/api/lounge/publish': typeof ApiLoungePublishRoute
  '/api/lounge/refresh': typeof ApiLoungeRefreshRoute
  '/api/lounge/report': typeof ApiLoungeReportRoute
  '/api/lounge/restore': typeof ApiLoungeRestoreRoute
  '/api/lounge/schedule': typeof ApiLoungeScheduleRoute
  '/api/lounge/session': typeof ApiLoungeSessionRoute
  '/api/lounge/status': typeof ApiLoungeStatusRoute
  '/api/phone/publish': typeof ApiPhonePublishRoute
  '/api/phone/queue': typeof ApiPhoneQueueRoute
  '/api/phone/session': typeof ApiPhoneSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/android'
    | '/config'
    | '/followers'
    | '/forensics'
    | '/insights'
    | '/login'
    | '/lounge'
    | '/new-feed'
    | '/phone'
    | '/publish'
    | '/reset-password'
    | '/stalker'
    | '/timing'
    | '/api/download-apk'
    | '/api/health'
    | '/api/auth/$'
    | '/api/cron/publish'
    | '/api/cron/pull'
    | '/api/lounge/dashboard'
    | '/api/lounge/hook'
    | '/api/lounge/link'
    | '/api/lounge/pair'
    | '/api/lounge/publish'
    | '/api/lounge/refresh'
    | '/api/lounge/report'
    | '/api/lounge/restore'
    | '/api/lounge/schedule'
    | '/api/lounge/session'
    | '/api/lounge/status'
    | '/api/phone/publish'
    | '/api/phone/queue'
    | '/api/phone/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/android'
    | '/config'
    | '/followers'
    | '/forensics'
    | '/insights'
    | '/login'
    | '/lounge'
    | '/new-feed'
    | '/phone'
    | '/publish'
    | '/reset-password'
    | '/stalker'
    | '/timing'
    | '/api/download-apk'
    | '/api/health'
    | '/api/auth/$'
    | '/api/cron/publish'
    | '/api/cron/pull'
    | '/api/lounge/dashboard'
    | '/api/lounge/hook'
    | '/api/lounge/link'
    | '/api/lounge/pair'
    | '/api/lounge/publish'
    | '/api/lounge/refresh'
    | '/api/lounge/report'
    | '/api/lounge/restore'
    | '/api/lounge/schedule'
    | '/api/lounge/session'
    | '/api/lounge/status'
    | '/api/phone/publish'
    | '/api/phone/queue'
    | '/api/phone/session'
  id:
    | '__root__'
    | '/'
    | '/android'
    | '/config'
    | '/followers'
    | '/forensics'
    | '/insights'
    | '/login'
    | '/lounge'
    | '/new-feed'
    | '/phone'
    | '/publish'
    | '/reset-password'
    | '/stalker'
    | '/timing'
    | '/api/download-apk'
    | '/api/health'
    | '/api/auth/$'
    | '/api/cron/publish'
    | '/api/cron/pull'
    | '/api/lounge/dashboard'
    | '/api/lounge/hook'
    | '/api/lounge/link'
    | '/api/lounge/pair'
    | '/api/lounge/publish'
    | '/api/lounge/refresh'
    | '/api/lounge/report'
    | '/api/lounge/restore'
    | '/api/lounge/schedule'
    | '/api/lounge/session'
    | '/api/lounge/status'
    | '/api/phone/publish'
    | '/api/phone/queue'
    | '/api/phone/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AndroidRoute: typeof AndroidRoute
  ConfigRoute: typeof ConfigRoute
  FollowersRoute: typeof FollowersRoute
  ForensicsRoute: typeof ForensicsRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  LoungeRoute: typeof LoungeRoute
  NewFeedRoute: typeof NewFeedRoute
  PhoneRoute: typeof PhoneRoute
  PublishRoute: typeof PublishRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StalkerRoute: typeof StalkerRoute
  TimingRoute: typeof TimingRoute
  ApiDownloadApkRoute: typeof ApiDownloadApkRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronPublishRoute: typeof ApiCronPublishRoute
  ApiCronPullRoute: typeof ApiCronPullRoute
  ApiLoungeDashboardRoute: typeof ApiLoungeDashboardRoute
  ApiLoungeHookRoute: typeof ApiLoungeHookRoute
  ApiLoungeLinkRoute: typeof ApiLoungeLinkRoute
  ApiLoungePairRoute: typeof ApiLoungePairRoute
  ApiLoungePublishRoute: typeof ApiLoungePublishRoute
  ApiLoungeRefreshRoute: typeof ApiLoungeRefreshRoute
  ApiLoungeReportRoute: typeof ApiLoungeReportRoute
  ApiLoungeRestoreRoute: typeof ApiLoungeRestoreRoute
  ApiLoungeScheduleRoute: typeof ApiLoungeScheduleRoute
  ApiLoungeSessionRoute: typeof ApiLoungeSessionRoute
  ApiLoungeStatusRoute: typeof ApiLoungeStatusRoute
  ApiPhonePublishRoute: typeof ApiPhonePublishRoute
  ApiPhoneQueueRoute: typeof ApiPhoneQueueRoute
  ApiPhoneSessionRoute: typeof ApiPhoneSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/android': {
      id: '/android'
      path: '/android'
      fullPath: '/android'
      preLoaderRoute: typeof AndroidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followers': {
      id: '/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof FollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forensics': {
      id: '/forensics'
      path: '/forensics'
      fullPath: '/forensics'
      preLoaderRoute: typeof ForensicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lounge': {
      id: '/lounge'
      path: '/lounge'
      fullPath: '/lounge'
      preLoaderRoute: typeof LoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-feed': {
      id: '/new-feed'
      path: '/new-feed'
      fullPath: '/new-feed'
      preLoaderRoute: typeof NewFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stalker': {
      id: '/stalker'
      path: '/stalker'
      fullPath: '/stalker'
      preLoaderRoute: typeof StalkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timing': {
      id: '/timing'
      path: '/timing'
      fullPath: '/timing'
      preLoaderRoute: typeof TimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-apk': {
      id: '/api/download-apk'
      path: '/api/download-apk'
      fullPath: '/api/download-apk'
      preLoaderRoute: typeof ApiDownloadApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/publish': {
      id: '/api/cron/publish'
      path: '/api/cron/publish'
      fullPath: '/api/cron/publish'
      preLoaderRoute: typeof ApiCronPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/pull': {
      id: '/api/cron/pull'
      path: '/api/cron/pull'
      fullPath: '/api/cron/pull'
      preLoaderRoute: typeof ApiCronPullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/dashboard': {
      id: '/api/lounge/dashboard'
      path: '/api/lounge/dashboard'
      fullPath: '/api/lounge/dashboard'
      preLoaderRoute: typeof ApiLoungeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/hook': {
      id: '/api/lounge/hook'
      path: '/api/lounge/hook'
      fullPath: '/api/lounge/hook'
      preLoaderRoute: typeof ApiLoungeHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/link': {
      id: '/api/lounge/link'
      path: '/api/lounge/link'
      fullPath: '/api/lounge/link'
      preLoaderRoute: typeof ApiLoungeLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/pair': {
      id: '/api/lounge/pair'
      path: '/api/lounge/pair'
      fullPath: '/api/lounge/pair'
      preLoaderRoute: typeof ApiLoungePairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/publish': {
      id: '/api/lounge/publish'
      path: '/api/lounge/publish'
      fullPath: '/api/lounge/publish'
      preLoaderRoute: typeof ApiLoungePublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/refresh': {
      id: '/api/lounge/refresh'
      path: '/api/lounge/refresh'
      fullPath: '/api/lounge/refresh'
      preLoaderRoute: typeof ApiLoungeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/report': {
      id: '/api/lounge/report'
      path: '/api/lounge/report'
      fullPath: '/api/lounge/report'
      preLoaderRoute: typeof ApiLoungeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/restore': {
      id: '/api/lounge/restore'
      path: '/api/lounge/restore'
      fullPath: '/api/lounge/restore'
      preLoaderRoute: typeof ApiLoungeRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/schedule': {
      id: '/api/lounge/schedule'
      path: '/api/lounge/schedule'
      fullPath: '/api/lounge/schedule'
      preLoaderRoute: typeof ApiLoungeScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/session': {
      id: '/api/lounge/session'
      path: '/api/lounge/session'
      fullPath: '/api/lounge/session'
      preLoaderRoute: typeof ApiLoungeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lounge/status': {
      id: '/api/lounge/status'
      path: '/api/lounge/status'
      fullPath: '/api/lounge/status'
      preLoaderRoute: typeof ApiLoungeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone/publish': {
      id: '/api/phone/publish'
      path: '/api/phone/publish'
      fullPath: '/api/phone/publish'
      preLoaderRoute: typeof ApiPhonePublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone/queue': {
      id: '/api/phone/queue'
      path: '/api/phone/queue'
      fullPath: '/api/phone/queue'
      preLoaderRoute: typeof ApiPhoneQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone/session': {
      id: '/api/phone/session'
      path: '/api/phone/session'
      fullPath: '/api/phone/session'
      preLoaderRoute: typeof ApiPhoneSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AndroidRoute: AndroidRoute,
  ConfigRoute: ConfigRoute,
  FollowersRoute: FollowersRoute,
  ForensicsRoute: ForensicsRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  LoungeRoute: LoungeRoute,
  NewFeedRoute: NewFeedRoute,
  PhoneRoute: PhoneRoute,
  PublishRoute: PublishRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StalkerRoute: StalkerRoute,
  TimingRoute: TimingRoute,
  ApiDownloadApkRoute: ApiDownloadApkRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronPublishRoute: ApiCronPublishRoute,
  ApiCronPullRoute: ApiCronPullRoute,
  ApiLoungeDashboardRoute: ApiLoungeDashboardRoute,
  ApiLoungeHookRoute: ApiLoungeHookRoute,
  ApiLoungeLinkRoute: ApiLoungeLinkRoute,
  ApiLoungePairRoute: ApiLoungePairRoute,
  ApiLoungePublishRoute: ApiLoungePublishRoute,
  ApiLoungeRefreshRoute: ApiLoungeRefreshRoute,
  ApiLoungeReportRoute: ApiLoungeReportRoute,
  ApiLoungeRestoreRoute: ApiLoungeRestoreRoute,
  ApiLoungeScheduleRoute: ApiLoungeScheduleRoute,
  ApiLoungeSessionRoute: ApiLoungeSessionRoute,
  ApiLoungeStatusRoute: ApiLoungeStatusRoute,
  ApiPhonePublishRoute: ApiPhonePublishRoute,
  ApiPhoneQueueRoute: ApiPhoneQueueRoute,
  ApiPhoneSessionRoute: ApiPhoneSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
